# src/resonarr/config/settings.py

import os

LIDARR_URL = os.getenv("LIDARR_URL")
LIDARR_API_KEY = os.getenv("LIDARR_API_KEY")

ROOT_FOLDER = os.getenv("LIDARR_ROOT_FOLDER", "/volume1/music/library")

QUALITY_PROFILE_NAME = os.getenv("LIDARR_QUALITY_PROFILE", "Lossless")
METADATA_PROFILE_NAME = os.getenv("LIDARR_METADATA_PROFILE", "Standard")

# --- Policy (MVP) ---

ACQUIRE_SCORE_THRESHOLD = int(os.getenv("RESONARR_ACQUIRE_THRESHOLD", 9))
RECOMMEND_SCORE_THRESHOLD = int(os.getenv("RESONARR_RECOMMEND_THRESHOLD", 4))
STAGED_RECOMMEND_SCORE_THRESHOLD = int(os.getenv("RESONARR_STAGED_RECOMMEND_THRESHOLD", 3))

# --- Cooldown / Backoff (MVP) ---

ARTIST_COOLDOWN_HOURS = int(os.getenv("RESONARR_ARTIST_COOLDOWN_HOURS", 24))
RECOMMENDATION_BACKOFF_HOURS = int(os.getenv("RESONARR_RECOMMENDATION_BACKOFF_HOURS", 72))
DASHBOARD_SNAPSHOT_TTL_SECONDS = int(os.getenv("RESONARR_DASHBOARD_SNAPSHOT_TTL_SECONDS", 60))
CATALOG_SNAPSHOT_TTL_SECONDS = int(os.getenv("RESONARR_CATALOG_SNAPSHOT_TTL_SECONDS", 300))
READ_API_HOST = os.getenv("RESONARR_READ_API_HOST", "127.0.0.1")
READ_API_PORT = int(os.getenv("RESONARR_READ_API_PORT", 8787))

# --- Plex ---

PLEX_BASE_URL = os.getenv("PLEX_BASE_URL")
PLEX_TOKEN = os.getenv("PLEX_TOKEN")
PLEX_MUSIC_LIBRARY = os.getenv("PLEX_MUSIC_LIBRARY", "Music")

LASTFM_API_KEY = os.getenv("LASTFM_API_KEY")
LASTFM_USERNAME = os.getenv("LASTFM_USERNAME")

# --- Signal Merge ---

SIGNAL_PLEX_WEIGHT = float(os.getenv("RESONARR_SIGNAL_PLEX_WEIGHT", 0.6))
SIGNAL_LASTFM_WEIGHT = float(os.getenv("RESONARR_SIGNAL_LASTFM_WEIGHT", 0.4))

SIGNAL_PLEX_PLAYS_HIGH = int(os.getenv("RESONARR_SIGNAL_PLEX_PLAYS_HIGH", 50))
SIGNAL_PLEX_PLAYS_MEDIUM = int(os.getenv("RESONARR_SIGNAL_PLEX_PLAYS_MEDIUM", 20))
SIGNAL_PLEX_PLAYS_LOW = int(os.getenv("RESONARR_SIGNAL_PLEX_PLAYS_LOW", 5))

SIGNAL_PLEX_MULTIPLIER_HIGH = float(os.getenv("RESONARR_SIGNAL_PLEX_MULTIPLIER_HIGH", 2.5))
SIGNAL_PLEX_MULTIPLIER_MEDIUM = float(os.getenv("RESONARR_SIGNAL_PLEX_MULTIPLIER_MEDIUM", 2.0))
SIGNAL_PLEX_MULTIPLIER_LOW = float(os.getenv("RESONARR_SIGNAL_PLEX_MULTIPLIER_LOW", 1.5))

SIGNAL_LASTFM_RATIO_HIGH = float(os.getenv("RESONARR_SIGNAL_LASTFM_RATIO_HIGH", 0.25))
SIGNAL_LASTFM_RATIO_MEDIUM = float(os.getenv("RESONARR_SIGNAL_LASTFM_RATIO_MEDIUM", 0.10))
SIGNAL_LASTFM_RATIO_LOW = float(os.getenv("RESONARR_SIGNAL_LASTFM_RATIO_LOW", 0.0))

SIGNAL_LASTFM_MULTIPLIER_HIGH = float(os.getenv("RESONARR_SIGNAL_LASTFM_MULTIPLIER_HIGH", 2.0))
SIGNAL_LASTFM_MULTIPLIER_MEDIUM = float(os.getenv("RESONARR_SIGNAL_LASTFM_MULTIPLIER_MEDIUM", 1.5))
SIGNAL_LASTFM_MULTIPLIER_LOW = float(os.getenv("RESONARR_SIGNAL_LASTFM_MULTIPLIER_LOW", 1.2))

# --- Deepen Automation ---

DEEPEN_LASTFM_PERIOD = os.getenv("RESONARR_DEEPEN_LASTFM_PERIOD", "1month")
DEEPEN_MAX_CANDIDATES = int(os.getenv("RESONARR_DEEPEN_MAX_CANDIDATES", 10))
DEEPEN_CANDIDATE_SCAN_LIMIT = int(os.getenv("RESONARR_DEEPEN_CANDIDATE_SCAN_LIMIT", 30))
DEEPEN_MIN_LASTFM_PLAYS = int(os.getenv("RESONARR_DEEPEN_MIN_LASTFM_PLAYS", 5))

DEEPEN_MAX_EVALUATIONS_PER_RUN = int(os.getenv("RESONARR_DEEPEN_MAX_EVALUATIONS_PER_RUN", 10))
DEEPEN_MAX_ACQUIRES_PER_RUN = int(os.getenv("RESONARR_DEEPEN_MAX_ACQUIRES_PER_RUN", 2))

PARTIAL_COMPLETION_BASE_BOOST = float(os.getenv("RESONARR_PARTIAL_COMPLETION_BASE_BOOST", 2.0))
PARTIAL_COMPLETION_MAX_BOOST = float(os.getenv("RESONARR_PARTIAL_COMPLETION_MAX_BOOST", 5.0))
PARTIAL_COMPLETION_CURVE_POWER = float(os.getenv("RESONARR_PARTIAL_COMPLETION_CURVE_POWER", 1.5))
PARTIAL_COMPLETION_MIN_RATIO = float(os.getenv("RESONARR_PARTIAL_COMPLETION_MIN_RATIO", 0.15))

# --- Extend Automation ---

EXTEND_LASTFM_PERIOD = os.getenv("RESONARR_EXTEND_LASTFM_PERIOD", "1month")
EXTEND_MIN_SEED_PLAYS = int(os.getenv("RESONARR_EXTEND_MIN_SEED_PLAYS", 10))
EXTEND_MAX_SEEDS = int(os.getenv("RESONARR_EXTEND_MAX_SEEDS", 10))
EXTEND_SIMILAR_PER_SEED = int(os.getenv("RESONARR_EXTEND_SIMILAR_PER_SEED", 10))
EXTEND_MAX_RECOMMENDATIONS = int(os.getenv("RESONARR_EXTEND_MAX_RECOMMENDATIONS", 20))
EXTEND_RECOMMENDATION_BACKOFF_HOURS = int(os.getenv("RESONARR_EXTEND_RECOMMENDATION_BACKOFF_HOURS", 168))
EXTEND_PROMOTION_MIN_SEEN_COUNT = int(os.getenv("RESONARR_EXTEND_PROMOTION_MIN_SEEN_COUNT", 2))
EXTEND_PROMOTION_MIN_SEED_COUNT = int(os.getenv("RESONARR_EXTEND_PROMOTION_MIN_SEED_COUNT", 2))
EXTEND_PROMOTION_MIN_MATCH_SCORE = float(os.getenv("RESONARR_EXTEND_PROMOTION_MIN_MATCH_SCORE", 0.75))
EXTEND_PROMOTION_MAX_PLANS_PER_RUN = int(os.getenv("RESONARR_EXTEND_PROMOTION_MAX_PLANS_PER_RUN", 3))

# --- Prune Automation ---

PRUNE_ENABLED = os.getenv("RESONARR_PRUNE_ENABLED", "false").lower() == "true"
PRUNE_DRY_RUN = os.getenv("RESONARR_PRUNE_DRY_RUN", "true").lower() == "true"

PRUNE_MATCH_MODE = os.getenv("RESONARR_PRUNE_MATCH_MODE", "mbid")
PRUNE_ALLOW_NAME_FALLBACK = os.getenv("RESONARR_PRUNE_ALLOW_NAME_FALLBACK", "false").lower() == "true"

PRUNE_TRACK_BAD_MAX_RATING = float(os.getenv("RESONARR_PRUNE_TRACK_BAD_MAX_RATING", 4.0))
PRUNE_MIN_TRACKS_RATED = int(os.getenv("RESONARR_PRUNE_MIN_TRACKS_RATED", 5))
PRUNE_ALBUM_BAD_RATIO = float(os.getenv("RESONARR_PRUNE_ALBUM_BAD_RATIO", 0.50))
PRUNE_UNRATED_TRACK_STRATEGY = os.getenv("RESONARR_PRUNE_UNRATED_TRACK_STRATEGY", "neutral")
PRUNE_ALLOW_SMALL_ALBUM_FULL_REJECT = (
    os.getenv("RESONARR_PRUNE_ALLOW_SMALL_ALBUM_FULL_REJECT", "true").lower() == "true"
)

PRUNE_ENABLE_ARTIST_PRUNE = os.getenv("RESONARR_PRUNE_ENABLE_ARTIST_PRUNE", "false").lower() == "true"
PRUNE_MAX_CANDIDATES_PER_RUN = int(os.getenv("RESONARR_PRUNE_MAX_CANDIDATES_PER_RUN", 100))
PRUNE_RESCAN_PLEX_AFTER_EXECUTION = (
    os.getenv("RESONARR_PRUNE_RESCAN_PLEX_AFTER_EXECUTION", "true").lower() == "true"
)
PRUNE_ADD_IMPORT_LIST_EXCLUSION = (
    os.getenv("RESONARR_PRUNE_ADD_IMPORT_LIST_EXCLUSION", "false").lower() == "true"
)
