# src/resonarr/config/settings.py

import os

LIDARR_URL = os.getenv("LIDARR_URL")
LIDARR_API_KEY = os.getenv("LIDARR_API_KEY")

ROOT_FOLDER = os.getenv("LIDARR_ROOT_FOLDER", "/volume1/music/library")

QUALITY_PROFILE_NAME = os.getenv("LIDARR_QUALITY_PROFILE", "Lossless")
METADATA_PROFILE_NAME = os.getenv("LIDARR_METADATA_PROFILE", "Standard")

# --- Policy (MVP) ---

ACQUIRE_SCORE_THRESHOLD = int(os.getenv("RESONARR_ACQUIRE_THRESHOLD", 9))
RECOMMEND_SCORE_THRESHOLD = int(os.getenv("RESONARR_RECOMMEND_THRESHOLD", 4))

# --- Cooldown (MVP) ---

ARTIST_COOLDOWN_HOURS = int(os.getenv("RESONARR_ARTIST_COOLDOWN_HOURS", 24))

# --- Plex ---

PLEX_BASE_URL = os.getenv("PLEX_BASE_URL")
PLEX_TOKEN = os.getenv("PLEX_TOKEN")
PLEX_MUSIC_LIBRARY = os.getenv("PLEX_MUSIC_LIBRARY", "Music")

LASTFM_API_KEY = os.getenv("LASTFM_API_KEY")
LASTFM_USERNAME = os.getenv("LASTFM_USERNAME")

# --- Signal Merge ---

SIGNAL_PLEX_WEIGHT = float(os.getenv("RESONARR_SIGNAL_PLEX_WEIGHT", 0.6))
SIGNAL_LASTFM_WEIGHT = float(os.getenv("RESONARR_SIGNAL_LASTFM_WEIGHT", 0.4))

SIGNAL_PLEX_PLAYS_HIGH = int(os.getenv("RESONARR_SIGNAL_PLEX_PLAYS_HIGH", 50))
SIGNAL_PLEX_PLAYS_MEDIUM = int(os.getenv("RESONARR_SIGNAL_PLEX_PLAYS_MEDIUM", 20))
SIGNAL_PLEX_PLAYS_LOW = int(os.getenv("RESONARR_SIGNAL_PLEX_PLAYS_LOW", 5))

SIGNAL_PLEX_MULTIPLIER_HIGH = float(os.getenv("RESONARR_SIGNAL_PLEX_MULTIPLIER_HIGH", 2.5))
SIGNAL_PLEX_MULTIPLIER_MEDIUM = float(os.getenv("RESONARR_SIGNAL_PLEX_MULTIPLIER_MEDIUM", 2.0))
SIGNAL_PLEX_MULTIPLIER_LOW = float(os.getenv("RESONARR_SIGNAL_PLEX_MULTIPLIER_LOW", 1.5))

SIGNAL_LASTFM_RATIO_HIGH = float(os.getenv("RESONARR_SIGNAL_LASTFM_RATIO_HIGH", 0.25))
SIGNAL_LASTFM_RATIO_MEDIUM = float(os.getenv("RESONARR_SIGNAL_LASTFM_RATIO_MEDIUM", 0.10))
SIGNAL_LASTFM_RATIO_LOW = float(os.getenv("RESONARR_SIGNAL_LASTFM_RATIO_LOW", 0.0))

SIGNAL_LASTFM_MULTIPLIER_HIGH = float(os.getenv("RESONARR_SIGNAL_LASTFM_MULTIPLIER_HIGH", 2.0))
SIGNAL_LASTFM_MULTIPLIER_MEDIUM = float(os.getenv("RESONARR_SIGNAL_LASTFM_MULTIPLIER_MEDIUM", 1.5))
SIGNAL_LASTFM_MULTIPLIER_LOW = float(os.getenv("RESONARR_SIGNAL_LASTFM_MULTIPLIER_LOW", 1.2))